
<img src="https://reqlut2.s3.sa-east-1.amazonaws.com/reqlut-images/duoc/logo.png?v=87.8" width="180px"/>

# Ejecución de Modelo Random Forest desde Archivo PKL

Este notebook tiene como objetivo cargar un modelo de clasificación Random Forest previamente entrenado y almacenado en formato .pkl, para posteriormente evaluar su rendimiento utilizando el conjunto de datos de prueba.

El modelo fue entrenado utilizando el conjunto de datos procesado del proyecto Student Depression Dataset.

## Objetivo

### Validar el desempeño del modelo entrenado mediante:

* Carga de los conjuntos de entrenamiento y prueba procesados.
* Recuperación del modelo serializado.
* Generación de predicciones sobre el conjunto de prueba.
* Evaluación mediante métricas de clasificación.

In [3]:
import sys
import os

"""
En caso de que Python no encuentre en la ruta los otros directorios,
ejecutar esta configuración
"""

sys.path.append(os.path.abspath(".."))

## Librerías utilizadas

In [ ]:
import pandas as pd
import joblib
from src.carga_csv import cargar_csv

| Librería | Propósito |
|-----------|-----------|
| pandas | Manipulación y carga de datos |
| joblib | Serialización y carga de modelos |
| scikit-learn | Métricas de evaluación |

In [12]:
model_rf = joblib.load(
    "../outputs/models/random_forest_model.pkl"
)

print("Modelo cargado correctamente.")

Modelo cargado correctamente.

In [5]:
preprocessor = joblib.load(
    r'..\outputs\models\preprocessor.pkl'
)

## Carga de Datos

Se cargan los conjuntos de entrenamiento y prueba previamente transformados durante la etapa de preprocesamiento.

In [6]:
df = cargar_csv(
    r"..\data\processed\Student_Depression_Dataset_Prediction.csv"
)

df.head()

,id,Gender,Age,City,Academic Pressure,CGPA,Study Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,1001,Male,22.0,Bangalore,3.0,7.45,4.0,5-6 hours,Moderate,BSc,No,5.0,2.0,No,0
1,1002,Female,24.0,Mumbai,5.0,6.12,2.0,Less than 5 hours,Unhealthy,M.Tech,Yes,10.0,5.0,Yes,1
2,1003,Male,29.0,Chennai,2.0,8.91,5.0,7-8 hours,Healthy,BE,No,3.0,1.0,No,0
3,1004,Female,21.0,Ahmedabad,4.0,7.03,3.0,5-6 hours,Moderate,B.Ed,Yes,8.0,4.0,Yes,1
4,1005,Male,31.0,Kolkata,1.0,9.12,5.0,More than 8 hours,Healthy,PhD,No,2.0,1.0,No,0

In [21]:
X_nuevo = preprocessor.transform(df)

X_nuevo = pd.DataFrame(
    X_nuevo,
    columns=preprocessor.get_feature_names_out()
)

## Generación de Predicciones

Una vez cargado el modelo, se generan predicciones sobre el conjunto de prueba.

In [22]:
predicciones = model_rf.predict(X_nuevo)

Cada predicción corresponde a una de las siguientes clases:

| Valor | Interpretación |
|---------|--------------|
| 0 | No presenta depresión |
| 1 | Presenta depresión |

In [23]:
predicciones

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [25]:
probabilidades = model_rf.predict_proba(X_nuevo)

probabilidades

array([[9.43616947e-01, 5.63830532e-02],
       [3.20998865e-04, 9.99679001e-01],
       [9.71085789e-01, 2.89142108e-02],
       [2.61868088e-02, 9.73813191e-01],
       [9.91782407e-01, 8.21759259e-03],
       [3.01755765e-03, 9.96982442e-01],
       [9.13928865e-01, 8.60711347e-02],
       [4.87371477e-02, 9.51262852e-01],
       [9.82559094e-01, 1.74409062e-02],
       [5.96590909e-03, 9.94034091e-01]])

In [26]:
resultado = df.copy()

resultado["Prediccion"] = predicciones
resultado["Prob_Depression"] = (
    model_rf.predict_proba(X_nuevo)[:, 1]
)

resultado

,id,Gender,Age,City,Academic Pressure,CGPA,Study Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression,Prediccion,Prob_Depression
0,1001,Male,22.0,Bangalore,3.0,7.45,4.0,5-6 hours,Moderate,BSc,No,5.0,2.0,No,0,0,0.056383
1,1002,Female,24.0,Mumbai,5.0,6.12,2.0,Less than 5 hours,Unhealthy,M.Tech,Yes,10.0,5.0,Yes,1,1,0.999679
2,1003,Male,29.0,Chennai,2.0,8.91,5.0,7-8 hours,Healthy,BE,No,3.0,1.0,No,0,0,0.028914
3,1004,Female,21.0,Ahmedabad,4.0,7.03,3.0,5-6 hours,Moderate,B.Ed,Yes,8.0,4.0,Yes,1,1,0.973813
4,1005,Male,31.0,Kolkata,1.0,9.12,5.0,More than 8 hours,Healthy,PhD,No,2.0,1.0,No,0,0,0.008218
5,1006,Female,20.0,Pune,5.0,5.85,2.0,Less than 5 hours,Unhealthy,Class 12,Yes,11.0,5.0,Yes,1,1,0.996982
6,1007,Male,27.0,Nashik,3.0,8.26,4.0,7-8 hours,Moderate,LLB,No,4.0,2.0,No,0,0,0.086071
7,1008,Female,23.0,Jaipur,4.0,6.48,3.0,5-6 hours,Healthy,MSc,Yes,9.0,4.0,Yes,1,1,0.951263
8,1009,Male,25.0,Srinagar,2.0,8.74,4.0,More than 8 hours,Moderate,BHM,No,3.0,1.0,No,0,0,0.017441
9,1010,Female,28.0,Nagpur,5.0,5.67,1.0,Less than 5 hours,Unhealthy,M.Pharm,Yes,12.0,5.0,Yes,1,1,0.994034